name: RevoMineableSpawners
version: 3.3.0
main: com.dnyferguson.mineablespawners.MineableSpawners
authors: [fergydanny, thiagogebrim]
description: A simplistic silk spawner plugin
softdepend: [Vault]
api-version: 1.13
commands:
  mineablespawners:
    aliases: [ms, mineablespawner]
    usage: /mineablespawners <give|set|reload>
    description: List spawner related commands.